device: "cuda"
dataset: 
    name: #"cifar100"/"aircraft"/"cub"
    reduced: false
    ex_4_class: 5
output_dim: 100
batch_size: 128
epochs: 200
seed: 42
model: "resnet18"
temperature: 0.1
geometry: #"euclidean"/"hyperspherical"/"poincare"
patience: 10
proto_opt: true
shrink_init: false
epsilon: 0
slope: 0
optimizer:
    name: "sgd"
    learning_rate: 0.1
    weight_decay: 0.001
    momentum: 0.9
lr_scheduler:
    steps:
        - 60
        - 140
        - 160
    entity: 0.2
logger:
    # type: "Local"
    # type: "Wandb"
    # wandb_args:
    #      project: "your-project"
    #      entity: "your-entity"
         
